# Generated by Django 5.1.6 on 2025-03-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producto",
            old_name="fecha_creacion",
            new_name="fecha_ingreso",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="fecha_actualizacion",
        ),
        migrations.AddField(
            model_name="producto",
            name="marca",
            field=models.CharField(default="Desconocida", max_length=50),
        ),
        migrations.AlterField(
            model_name="producto",
            name="cantidad",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="producto",
            name="nombre",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
