# Generated by Django 5.1.6 on 2025-03-28 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0002_rename_fecha_creacion_producto_fecha_ingreso_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="descripcion",
        ),
    ]
