# Generated by Django 5.1.6 on 2025-03-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0003_remove_producto_descripcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="productos/"),
        ),
    ]
